package com.equipo.controller;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.equipo.dao.AseguradoraDao;
import com.equipo.model.Aseguradora;

import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.TableView;
import javafx.stage.Stage;

public class GenerarInformeMensualController {
	@FXML
	private Label lblMes;
	@FXML
	private DatePicker picMes;
	@FXML
	private Label lblEmpresaAseguradora;
	@FXML
	private ComboBox<Aseguradora> cboEmpresaAseguradora;
	@FXML
	private Button btnGenerarInforme;
	@FXML
	private Button btnImprimirInforme;
	@FXML
	private TableView tblServicio;
	
	@FXML
	public void initialize() {
				
		AseguradoraDao ase = new AseguradoraDao();
		ObservableList<Aseguradora> list = ase.obtenerTodos();
		
		cboEmpresaAseguradora.getItems().clear();
		cboEmpresaAseguradora.setItems(list);
		cboEmpresaAseguradora.getSelectionModel().select(0);
	}
	
	// Event Listener on DatePicker[#picMes].onAction
	@FXML
	public void clkMes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#cboEmpresaAseguradora].onAction
	@FXML

	public void slcAseguradora(ActionEvent event) {
		// TODO Autogenerated
	}

	public void btnGenerarInforme(ActionEvent event) {
	//sessionFactory.close();

	}
	
	public void closeWindow() {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/Main.fxml"));
			
			Parent root = loader.load();
			
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			
			stage.setScene(scene);
	        stage.setTitle("Administración de Turnos");
			stage.show();
			
			Stage myStage = (Stage) this.lblMes.getScene().getWindow();
			myStage.close();
			
			myStage.close();
		} catch (IOException ex) {
			Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	
}
