package com.equipo.controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.equipo.dao.AseguradoraDao;
import com.equipo.model.Aseguradora;
import com.equipo.model.Mecanico;
import com.equipo.model.Mecanico.Especialidad;

import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.DatePicker;

import javafx.scene.control.TableView;
import javafx.stage.Stage;

public class GenerarInformeDiarioController {
	@FXML
	private DatePicker dpkFecha;
	@FXML
	private ComboBox<Especialidad> ddEspecialidad;
	@FXML
	private Button btnGenerarInforme;
	@FXML
	private Button btnImprimirInforme;
	@FXML
	private TableView tblServicio;

	@FXML
	public void initialize() {
		
		ddEspecialidad.getItems().setAll(Mecanico.Especialidad.values());
		ddEspecialidad.getSelectionModel().select(0);
	}
	
	// Event Listener on Button[#btnGenerarInforme].onAction
	@FXML
	public void clkGenerarInformeDiario(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnImprimirInforme].onAction
	@FXML
	public void clkImprimirInformeDiario(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void closeWindow() {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/Main.fxml"));
			
			Parent root = loader.load();
			
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			
			stage.setScene(scene);
	        stage.setTitle("Administración de Turnos");
			stage.show();
			
			Stage myStage = (Stage) this.dpkFecha.getScene().getWindow();
			myStage.close();
			
			myStage.close();
		} catch (IOException ex) {
			Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
}
