package com.equipo.controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ComboBox;

import javafx.scene.control.DatePicker;

import javafx.scene.control.TableView;
import javafx.stage.Stage;

public class InformeMensualController {
	@FXML
	private Label lblMes;
	@FXML
	private DatePicker picMes;
	@FXML
	private Label lblEmpresaAseguradora;
	@FXML
	private ComboBox cboEmpresaAseguradora;
	@FXML
	private Button btnGenerarInforme;
	@FXML
	private Button btnImprimirInforme;
	@FXML
	private TableView tblServicio;

	// Event Listener on DatePicker[#picMes].onAction
	@FXML
	public void clkMes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#cboEmpresaAseguradora].onAction
	@FXML
	public void slcAseguradora(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void closeWindows() {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/Main.fxml"));
			
			Parent root = loader.load();
			
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			
			stage.setScene(scene);
	        stage.setTitle("Administración de Turnos");
			stage.show();
			
			Stage myStage = (Stage) this.lblMes.getScene().getWindow();
			myStage.close();
			
			myStage.close();
		} catch (IOException ex) {
			Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	
}
