package com.equipo.controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.DatePicker;

import javafx.scene.control.TableView;

public class MostrarServicioController {
	@FXML
	private Label lblFecha;
	@FXML
	private Button btnBuscar;
	@FXML
	private Label lblNroServicio;
	@FXML
	private TextField txtNroServicio;
	@FXML
	private DatePicker picFecha;
	@FXML
	private TableView tblServicios;
	@FXML
	private Button btnCargarPlanilla;
	@FXML
	private Button btnGenerarConstancia;
	@FXML
	private Button btnCancelar;
	@FXML
	private Button btnImprimi;

	// Event Listener on Button[#btnCargarPlanilla].onAction
	@FXML
	public void clkCargarPlanilla(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/CargarPlanillaDeTrabajo.fxml"));
			
			Parent root = loader.load();
			
			CargarPlanillaDeTrabajoController controlador = loader.getController();
			
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			
			stage.setScene(scene);
			stage.setTitle("Cargar planilla");
			stage.show();
			
			stage.setOnCloseRequest(e -> controlador.closeWindow());
			
			Stage myStage = (Stage) this.lblFecha.getScene().getWindow();
			
			myStage.close();
		} catch (IOException ex) {
			Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	// Event Listener on Button[#btnCerraPlanilla].onAction
	@FXML
	public void clkCerrarPlanilla(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnImprimi].onAction
	@FXML
	public void clkImprimirFicha(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/ImprimirFicha.fxml"));
			
			Parent root = loader.load();
			
			ImprimirFichaController controlador = loader.getController();
			
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			
			stage.setScene(scene);
			stage.setTitle("Imprimir ficha");
			stage.show();
			
			stage.setOnCloseRequest(e -> controlador.closeWindow());
			
			Stage myStage = (Stage) this.lblFecha.getScene().getWindow();
			
			myStage.close();
		} catch (IOException ex) {
			Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	
	public void closeWindow() {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/Main.fxml"));
			
			Parent root = loader.load();
			
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			
			stage.setScene(scene);
	        stage.setTitle("Administración de Turnos");
			stage.show();
			
			Stage myStage = (Stage) this.lblFecha.getScene().getWindow();
			myStage.close();
			
			myStage.close();
		} catch (IOException ex) {
			Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
}
