package com.equipo.controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.DatePicker;

import javafx.scene.control.TableView;

public class MostrarTurnosController {
	@FXML
	private Label lblFecha;
	@FXML
	private Button btnBuscar;
	@FXML
	private Label lblNroTurno;
	@FXML
	private TextField txtNroTurno;
	@FXML
	private DatePicker picFecha;
	@FXML
	private TableView tblTurnos;
	@FXML
	private Button btnNuevoTurno;
	@FXML
	private Button btnEditarTurno;
	@FXML
	private Button btnEliminarTurno;
	@FXML
	private Button btnRegistrarAsistencia;
	@FXML
	private Button btnCancelar;

	// Event Listener on Button[#btnNuevoTurno].onAction
	@FXML
	public void clkNuevoTurno(ActionEvent event) throws IOException {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/NuevoTurno.fxml"));
			
			Parent root = loader.load();
			
			NuevoTurnoController controlador = loader.getController();
			
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			
			stage.setScene(scene);
			stage.setTitle("Nuevo turno");
			stage.show();
			
			stage.setOnCloseRequest(e -> controlador.closeWindow());
			
			Stage myStage = (Stage) this.lblFecha.getScene().getWindow();
			
			myStage.close();
		} catch (IOException ex) {
			Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	// Event Listener on Button[#btnEditarTurno].onAction
	@FXML
	public void clkEditarTurno(ActionEvent event) throws IOException {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/EditarTurno.fxml"));
			
			Parent root = loader.load();
			
			EditarTurnoController controlador = loader.getController();
			
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			
			stage.setScene(scene);
			stage.setTitle("Editar turno");
			stage.show();
			
			stage.setOnCloseRequest(e -> {
				try {
					controlador.closeWindow();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			});
			
			Stage myStage = (Stage) this.lblFecha.getScene().getWindow();
			
			myStage.close();
		} catch (IOException ex) {
			Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	// Event Listener on Button[#btnEliminarTurno].onAction
	@FXML
	public void clkEliminarTurno(ActionEvent event) throws IOException {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/EliminarTurno.fxml"));
			
			Parent root = loader.load();
			
			EliminarTurnoController controlador = loader.getController();
			
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			
			stage.setScene(scene);
			stage.setTitle("Servicios");
			stage.show();
			
			stage.setOnCloseRequest(e -> {
				try {
					controlador.closeWindow();
				} catch (IOException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			});
			
			Stage myStage = (Stage) this.lblNroTurno.getScene().getWindow();
			
			myStage.close();
		} catch (IOException ex) {
			Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
	// Event Listener on Button[#btnRegistrarAsistencia].onAction
	@FXML
	public void clkRegistrarAsistencia(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void closeWindow() throws IOException {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/Main.fxml"));
			
			Parent root = loader.load();
			
			Scene scene = new Scene(root);
			Stage stage = new Stage();
			
			stage.setScene(scene);
	        stage.setTitle("Administración de Turnos");
			stage.show();
			
			Stage myStage = (Stage) this.lblNroTurno.getScene().getWindow();
			myStage.close();
			
			myStage.close();
		} catch (IOException ex) {
			Logger.getLogger(MainController.class.getName()).log(Level.SEVERE, null, ex);
		}
	}
}
